// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xzgbdaejjcdusbtwejom.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6Z2JkYWVqamNkdXNidHdlam9tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2MDAwNTAsImV4cCI6MjA1OTE3NjA1MH0.WBq0Z0GivQ9U887f2rxXpR3chOS5QMp6mO1b-KFfzTM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);