
name: Build and Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      
      # Force clean install to resolve dependency issues
      - name: Clean npm cache
        run: npm cache clean --force
        
      - name: Remove package-lock.json
        run: rm -f package-lock.json
        
      - name: Install dependencies with clean slate
        run: npm install --no-fund --no-audit
      
      # Explicitly install required packages
      - name: Install required packages explicitly
        run: npm install --save-dev @vitejs/plugin-react terser@latest lovable-tagger@latest @vercel/analytics@latest @testing-library/react vitest jsdom
      
      - name: Build
        run: npm run build
        env:
          NODE_ENV: production
          BASE_URL: /
      
      - name: Test
        run: npm test || echo "No tests specified"
