
name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Need full history for GitHub Pages
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install required packages explicitly
        run: npm install --save-dev @vitejs/plugin-react terser@latest
      
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4
      
      - name: Build
        run: npm run build
        env:
          NODE_ENV: production
          # Set base path to / for custom domain
          BASE_URL: /
      
      - name: Copy CNAME to dist
        run: |
          echo "planodeparto.energiamaterna.com.br" > dist/CNAME
          echo "CNAME file created successfully"
      
      - name: Copy 404.html to dist root
        run: |
          if [ -f "public/404.html" ]; then
            cp public/404.html dist/
            echo "404.html file copied successfully"
          else
            echo "404.html file not found in public directory"
          fi
        
      - name: Copy domain-test.txt to dist root
        run: |
          echo "Domain test file for planodeparto.energiamaterna.com.br - $(date)" > dist/domain-test.txt
          echo "Domain test file created successfully"
      
      - name: Create .nojekyll file
        run: touch dist/.nojekyll
      
      - name: Check for symlinks
        run: |
          echo "Checking for symlinks in the dist directory..."
          find dist -type l -ls || true
      
      - name: List build directory contents
        run: ls -la dist/
      
      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist
          
  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
